import { Hero } from './hero';

export const HEROES: Hero[] = [
  {  id:1 , photoS: 'https://i.annihil.us/u/prod/marvel/i/mg/9/30/538cd33e15ab7/standard_xlarge.jpg' ,photoG:'https://i.annihil.us/u/prod/marvel/i/mg/6/60/538cd3628a05e.jpg', nick:'Spider-Man' , details:'Bitten by a radioactive spider, high school student Peter Parker gained the speed, strength and powers of a spider. Adopting the name Spider-Man, Peter hoped to start a career using his new abilities. Taught that with great power comes great responsibility, Spidey has vowed to use his powers to help people. ' , realName:'Peter Benjamin Parker' ,height:'5\'10"', weight:'167 lbs.', powers:'Peter can cling to most surfaces, has superhuman strength (able to lift 10 tons optimally) and is roughly 15 times more agile than a regular human. The combination of his acrobatic leaps and web-slinging enables him to travel rapidly from place to place. His spider-sense provides an early warning detection system linked with his superhuman kinesthetics, enabling him the ability to evade most any injury, provided he doesn\'t cognitively override the autonomic reflexes. Note: his power enhancements through his transformation by the Queen and after battling Morlun - including his organic web glands and stingers - have been undone after Spider-Man\'s deal with Mephisto.', abilities:'Peter is an accomplished scientist, inventor and photographer.', affiliations:'Avengers, formerly the Secret Defenders, "New Fantastic Four", the Outlaws', first:'Amazing Fantasy #15 (1962)',origin:'Amazing Fantasy #15 (1962)'},
  {  id:2 , photoS: 'https://i.annihil.us/u/prod/marvel/i/mg/c/10/537ba5ff07aa4/standard_xlarge.jpg',  photoG: 'https://i.annihil.us/u/prod/marvel/i/mg/6/30/537ba61b764b4.jpg'  , nick:'Captain Marvel' , details:'Carol Danvers entered the Air Force upon graduating from high school to pursue her love of aircrafts and her dreams of flying. Carol was a top student at the Air Force Academy and enjoyed a rapid career advancement rising to the rank of Major. Because of her stellar performance, superb combat skills and natural intellect, Carol was recruited into the intelligence field. She ended up serving with the C.I.A., during which time she met and worked with Colonel Nick Fury. ', realName:'Carol Danvers' ,height:'5\'11"', weight:'165 lbs.', powers:'Ms. Marvel\'s current powers include flight, enhanced strength, durability and the ability to shoot concussive energy bursts from her hands.', abilities:'Ms. Marvel is a skilled pilot & hand to hand combatant', affiliations:'Avengers; formerly Queen\'s Vengeance, Starjammers', first:'Marvel Super-Heroes #13 (1967)',origin:'Marvel Super Heroes #18, Ms. Marvel #1(2006)'},
  {  id:3 , photoS: 'https://i.annihil.us/u/prod/marvel/i/mg/5/a0/538615ca33ab0/standard_xlarge.jpg',  photoG: 'https://i.annihil.us/u/prod/marvel/i/mg/e/e0/537bafa34baa9.jpg' , nick:'Hulk' , details:'Caught in a gamma bomb explosion while trying to save the life of a teenager, Dr. Bruce Banner was transformed into the incredibly powerful creature called the Hulk. An all too often misunderstood hero, the angrier the Hulk gets, the stronger the Hulk gets.' , realName:'Robert Bruce Banner' ,height:'5\'9½" (Banner); 6\'6" (gray Hulk); 7\' – 8\' (green/savageHulk); 7\'6" (green/Professor Hulk)', weight:'128 lbs. (Banner); 900 lbs. (gray Hulk); 1,040 – 1,400 lbs.(green/savage Hulk); 1,150 lbs. (green/Professor Hulk)', powers:'The Hulk possesses an incredible level of superhuman physical ability. His capacity for physical strength is potentially limitless due to the fact that the Hulk\'s strength increases proportionally with his level of great emotional stress, anger in particular. The Hulk uses his superhumanly strong leg muscles to leap great distances. The Hulk has been known to cover hundreds of miles in a single bound and once leaped almost into orbit around the Earth. The Hulk can also use his superhumanly leg muscles to run at super speeds, although his legs have limitless strength he does not have limitless speed and once he reaches a certain speed his legs become too strong and destroy the ground giving him no friction to run on, therefore he jumps to travel. The Hulk can slam his hands together creating a shock wave, this shock wave can deafen people, send objects flying and extinguish fires. His thunderclap has been compared to hurricanes and sonic booms. The Hulk has shown a high resistance to physical damage nearly regardless of the cause, and has also shown resistance to extreme temperatures, mind control, nuclear explosions, poisons, and all diseases. In addition to the regeneration of limbs, vital organs, and damaged or destroyed areas of tissue at an amazing rate. The Hulk also has superhuman endurance.The Hulk\'s body also has a gland that makes an "oxygenated per fluorocarbon emulsion", which creates pressure in the Hulk\'s lungs and effectively lets him breathe underwater and move quickly between varying depths without concerns about decompression or nitrogen narcosis.', abilities:'Dr. Bruce Banner is a genius in nuclear physics, possessing a mind so brilliant that it cannot be measured on any known intelligence test. When Banner is the Hulk, Banner\'s consciousness is buried within the Hulk\'s, and can influence the Hulk\'s behavior only to a very limited extent.', affiliations:'Formerly Avengers, Defenders, Fantastic Four, Pantheon, Horsemen of Apocalypse, Warbound', first:'Incredible Hulk #1 (1962)',origin:'Incredible Hulk #1 (1962)'},
  {  id:4 , photoS: '',  photoG: ''  , nick:'' , details:'' , realName:'' ,height:'', weight:'', powers:'', abilities:'', affiliations:'', first:'',origin:''},
  {  id:5 , photoS: '',  photoG: ''  , nick:'' , details:'' , realName:'' ,height:'', weight:'', powers:'', abilities:'', affiliations:'', first:'',origin:''},
  {  id:6 ,photoS: '',  photoG: ''   , nick:'' , details:'' , realName:'' ,height:'', weight:'', powers:'', abilities:'', affiliations:'', first:'',origin:''},
  {  id:7 , photoS: '',  photoG: ''  , nick:'' , details:'' , realName:'' ,height:'', weight:'', powers:'', abilities:'', affiliations:'', first:'',origin:''}
];

